# reCBZ.Archive defaults
[archive]
# General options
# ---------------------------------------------------------------------
# whether to overwrite the original archive. dangerous
overwrite = false
# ignore errors when overwrite is true. very dangerous
ignore = false
# level of logging: -1 = quiet. 0 = overlapping progress report. 1 = streaming
# progress report. 2 = verbose messages. >2 = everything
loglevel = 0
# whether to enable multiprocessing
parallel = true
# max number of processes to spawn. 0 will use all available CPUs
processes = 0
# default format to save archives as
outformat = 'cbz'
# whether to further compress the zipfile after repacking
compresszip = false
# number of images to sample when comparing image formats
samplecount = 10
# dry run. archive won't be saved, even if overwrite is used
nowrite = false
# whether to print the 'recbz.py' title at the beginning
showtitle = true
# space separated list of formats to exclude from --compare
blacklistedfmts = ''

# Options which affect image quality and/or file size:
# ---------------------------------------------------------------------
# default format to convert images to. leave empty to preserve original
imageformat = ''
# compression quality for lossy images
quality = 80
# new image width / height. set to 0x0 to preserve original dimensions
resolution = "0x0"
# set to True to disable upscaling of images smaller than resolution
noupscale = false
# set to True to disable downscaling of images larger than resolution
nodownscale = false
# whether to convert images to grayscale
grayscale = false
